AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for Histoday static website hosting

Resources:
  HistodayBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub histoday-public-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      AccessControl: PublicRead

  HistodayBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HistodayBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${HistodayBucket}/*"

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref HistodayBucket

  WebsiteURL:
    Description: URL of the static website
    Value: !GetAtt HistodayBucket.WebsiteURL
